<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8"/>
		<title>All Appointments</title>
		<script type="text/javascript" src="//cdn.jsdelivr.net/jquery/1/jquery.min.js"></script>
		<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.13/css/jquery.dataTables.min.css" />
		<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/bootstrap/3/css/bootstrap.css" />
		<script type="text/javascript" src="https://cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js"></script>
		<script>
			$(document).ready(function(){
				$('#appointments-table').DataTable();
			});
		</script>
	</head>
	<body>
		<div class="container">
			<div class="row">
				<div class="col-md-10">
			<h2>All Appointments </h2>
		<table id="appointments-table" class="display" cellspacing="0" width="100%">
			<thead>
				<tr>
					<th>Appointment ID</th>
					<th>Appointment Date/Time</th>
					<th>Details</th>
					<th>Created At</th>
					<th>Actions</th>
				</tr>
			</thead>
			<tfoot>
				<tr>
					<th>Appointment ID</th>
					<th>Appointment Date/Time</th>
					<th>Details</th>
					<th>Created At</th>
					<th>Actions</th>
				</tr>
			</tfoot>
			<tbody>
			<?php foreach( $appointments as $appointment ) { ?>
			<tr>
				<td><?php echo $appointment->getAppointmentId(); ?></td>
				<td><?php echo $appointment->getAppointmentDateTime(); ?></td>
				<td><?php echo $appointment->getAppointmentDetails(); ?></td>
				<td><?php echo $appointment->getCreatedAt()->format("m/d/Y H:00 A"); ?></td>
				<td>
					<a href="/appointment/<?php echo $appointment->getAppointmentId(); ?>">
						<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
					</a>
					<form method="POST" action="/appointment/delete">
						<input type="hidden" name="appointment-id" value="<?php echo $appointment->getAppointmentId(); ?>" />
						<button type="submit" class="btn btn-danger">
							<i class="glyphicon glyphicon-trash"></i> 
						</button>
					</form>
					
				</td>
			</tr>
			<?php } ?>
			</tbody>
		</table>
		</div>
		</div>
		</div>
		
	</body>
		
<?php
/*
foreach( $appointments as $appointment ) {
	$appointmentId = $appointment->getAppointmentId();
	$dateTime = $appointment->getAppointmentDateTime();
	$details = $appointment->getAppointmentDetails();
	$createdAt = $appointment->getCreatedAt();
	
	// User Object
	$firstName = $appointment->getUser()->getFirstName();
	$lastName = $appointment->getUser()->getLastName();
	
	var_dump($createdAt);
	
}
*/
?>
</html>
