<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8"/>
		<title>User Profile</title>
		<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
		<script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	</head>
	<body>
	<div class="container">
		<!-- This flash notification here is a bit of a hack, but works for demo purposes 
			 solution would be improved upon with AJAX updating -->
		<?php if ($_SERVER['HTTP_REFERER']) { ?>
		<div class="alert alert-success" role="alert">
			<strong>Congratulations!</strong> Your profile has been updated.
		</div>
		<?php } ?>
		<h1>User Profile</h1>
		<form method="POST" action="/user/profile">
		<div class="form-group row">
		<label for="lgFormGroupInput" class="col-sm-2 col-form-label col-form-label-lg">First Name</label>
		<div class="col-sm-4">
			<input type="text" name="first-name" value="<?php echo $user->getFirstName(); ?>" class="form-control form-control-lg" id="first-name" placeholder="First Name">
			</div>
		</div>
		<div class="form-group row">
		<label for="smFormGroupInput" class="col-sm-2 col-form-label col-form-label-sm">Last Name</label>
			<div class="col-sm-4">
			<input type="text" name="last-name" value="<?php echo $user->getLastName(); ?>" class="form-control form-control-sm" id="last-name" placeholder="Last Name">
			</div>
		</div>
		<div class="form-group row">
		<label for="example-datetime-local-input" class="col-sm-2 col-form-label col-form-label-sm">Created At</label>
			<div class="col-sm-4">
				<input type="text" name="created-at" value="<?php echo $user->getCreatedAt()->format('Y-m-d H:i:s'); ?>" class="form-control form-control-sm" value="" id="created-at" readonly>
			</div>
		</div>
		<input type="hidden" name="user-id" value="<?php echo $user->getUserId(); ?>" />
		<button type="submit" class="btn btn-primary">Update Profile</button>
		</form>
	</div>
	</body>
</html>